name := "sbt-ScalablyTyped"
organization := "org.scalablytyped"
version := "201906181247"
sbtPlugin := true
scalaVersion := "2.13.0"
bintrayRepository := "ScalablyTyped"
licenses += ("MIT", url("http://opensource.org/licenses/MIT"))
publishMavenStyle := true
crossSbtVersions := Vector("0.13.16", "1.2.8")
